title: "我的 GitHub 博客"
description: "使用 GitHub Issues 生成的博客"
baseurl: ""
url: "https://echo-mo.github.io"
github_username: echo-mo

# theme: minima
plugins:
  - jekyll-feed

markdown: kramdown
permalink: pretty

collections:
  posts:
    output: true
    permalink: /blog/:path/