name: Generate Blog from Issues

on:
  issues:
    types: [opened, edited, labeled]
  workflow_dispatch:

jobs:
  generate-blog:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'blog')
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Generate blog post
      run: |
        python .github/scripts/generate_post.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        ISSUE_TITLE: '${{ github.event.issue.title }}'
        ISSUE_BODY: '${{ github.event.issue.body }}'
        
    - name: Setup Jekyll
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        
    - name: Build site
      run: |
        gem install jekyll
        jekyll build
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site