name: Build Blog from Issues

on:
  issues:
    types: [opened, edited, labeled]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install Python dependencies
      run: pip install PyGithub
        
    - name: Generate blog posts from issues
      run: python scripts/issue_to_post.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        
    # 使用 Ruby setup action 正确安装 Jekyll
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true

    - name: Install Jekyll and dependencies
      run: |
        gem install jekyll
        gem install bundler
        
    - name: Build Jekyll site
      run: |
        jekyll --version
        jekyll build --trace
        
    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: _site/
        
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3