name: Deploy Blog to GitHub Pages

on:
  push:
    branches: ["main"]
  issues:
    types: [opened, edited, labeled]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate blog posts
        if: github.event_name == 'issues' && contains(github.event.issue.labels.*.name, 'blog')
        run: |
          echo "生成博客文章..."
          python .github/scripts/generate_post.py
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: '${{ github.event.issue.title }}'
          ISSUE_BODY: '${{ github.event.issue.body }}'

      - name: Setup Jekyll with Bundler
        run: |
            gem install bundler
            bundle config set --local path 'vendor/bundle'
            bundle install

      - name: Build site
        run: |
          jekyll build --trace

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3